name: 'shop-web'
port: 8021
user_server:
  host: '127.0.0.1'
  port: 5005

goods_server:
  host: '127.0.0.1'
  port: 5006

jwt:
  key: '996948441'


nacos:
  host: '127.0.0.1'
  port: 8848
  namespace: '65424d7a-f310-4aa8-b2a1-e14095f73442'
  user: 'nacos'
  password: 'nacos'
  dataid: 'config.json'
  group: 'dev'

consul:
  host: '127.0.0.1'
  port: 8500
  scheme: 'http'
  token: ''
  datacenter: 'dc1'
  wait_time: '30s'